timeout: 0

/Socrates BSD 9
    protocol: limine
    kernel_path: boot():/boot/kernel
    module_path: boot():/boot/initrd.tar
    framebuffer_width: 1024
    framebuffer_height: 768
    framebuffer_bpp: 32
