/*
 * gcrypttest — libgcrypt in ring 3.
 *
 * The library is upstream and its algorithms are not in question; what
 * is in question is this *port* of it, which is a hand-written config.h,
 * four headers generated by tools run at build time, a freestanding C
 * library underneath, and the whole of the assembly turned off. So the
 * checks are chosen for what each would catch if one of those were
 * subtly wrong.
 *
 *   Published vectors, not round trips. Every digest and cipher below is
 *   checked against a number printed in a standard — FIPS 197, RFC 4231,
 *   RFC 6070, NIST's own SHA examples — because an encrypt/decrypt round
 *   trip agrees with itself even when both halves share a wrong idea of
 *   the S-box. This matters more here than in a normal build: the
 *   portable C paths are the ones running, and on a distribution build
 *   they usually are not.
 *
 *   The errno table, which is the one thing in this port that could be
 *   wrong in a way nothing else would reveal. libgpg-error maps C errno
 *   values onto GPG_ERR_* codes through a table generated at build time
 *   by preprocessing errnos.in — and it has to be preprocessed with the
 *   *cross* compiler, against libc/include/errno.h, because this
 *   system's numbers are Linux's and the build machine's are not.
 *   EOPNOTSUPP is 95 here and 102 on macOS. Generated with the wrong
 *   preprocessor, every gpg_error_from_errno would be silently wrong and
 *   every algorithm below would still pass.
 *
 *   The secure-memory pool and the random generator, because both touch
 *   the parts of this system libgcrypt cannot assume: there is no mlock,
 *   and entropy comes from getentropy over SYS_RANDOM rather than from
 *   /dev/random or a jitter loop.
 */

#include "vextro.h"

#include <errno.h>
#include <stdio.h>
#include <string.h>

#include <gcrypt.h>

static int checks = 0, failures = 0;

static void check(const char *what, int good) {
    checks++;
    if (!good) { failures++; printf("  FAIL  %s\n", what); }
}

/* Compare against a vector written as hex, which is how every standard
 * prints one — so the constant in this file can be read against the
 * document without converting anything. */
static int hexeq(const unsigned char *got, const char *hex, size_t n) {
    for (size_t i = 0; i < n; i++) {
        int hi = hex[i * 2], lo = hex[i * 2 + 1];
        hi = (hi <= '9') ? hi - '0' : (hi | 32) - 'a' + 10;
        lo = (lo <= '9') ? lo - '0' : (lo | 32) - 'a' + 10;
        if (got[i] != (unsigned char)((hi << 4) | lo)) return 0;
    }
    return 1;
}

int main(void) {
    printf("gcrypttest: libgcrypt %s in ring 3\n", GCRYPT_VERSION);

    /* ---- 1. the library comes up ---- */
    const char *ver = gcry_check_version(GCRYPT_VERSION);
    check("gcry_check_version accepts its own version", ver != NULL);
    check("and returns the version string",
          ver && strcmp(ver, GCRYPT_VERSION) == 0);

    /*
     * Secure memory. There is no mlock on this system, so the pool is
     * ordinary memory that is wiped on release rather than pinned memory
     * — third_party/libgcrypt-port/config.h says so at length. What is
     * checked here is that initialising it *succeeds* anyway, because
     * libgcrypt is entitled to refuse to run without it.
     */
    gcry_control(GCRYCTL_SUSPEND_SECMEM_WARN);
    gcry_control(GCRYCTL_INIT_SECMEM, 16384, 0);
    gcry_control(GCRYCTL_RESUME_SECMEM_WARN);
    gcry_control(GCRYCTL_INITIALIZATION_FINISHED, 0);
    check("the library finished initialising", gcry_control(GCRYCTL_INITIALIZATION_FINISHED_P) != 0);

    /* ---- 2. digests, against the standards' own vectors ---- */
    {
        unsigned char d[64];
        /* NIST's one-block SHA-256 example. */
        gcry_md_hash_buffer(GCRY_MD_SHA256, d, "abc", 3);
        check("SHA-256(\"abc\") matches NIST",
              hexeq(d, "ba7816bf8f01cfea414140de5dae2223"
                       "b00361a396177a9cb410ff61f20015ad", 32));

        gcry_md_hash_buffer(GCRY_MD_SHA1, d, "abc", 3);
        check("SHA-1(\"abc\") matches FIPS 180",
              hexeq(d, "a9993e364706816aba3e25717850c26c9cd0d89d", 20));

        gcry_md_hash_buffer(GCRY_MD_SHA512, d, "abc", 3);
        check("SHA-512(\"abc\") matches FIPS 180",
              hexeq(d, "ddaf35a193617abacc417349ae204131"
                       "12e6fa4e89a97ea20a9eeee64b55d39a"
                       "2192992a274fc1a836ba3c23a3feebbd"
                       "454d4423643ce80e2a9ac94fa54ca49f", 64));

        gcry_md_hash_buffer(GCRY_MD_MD5, d, "abc", 3);
        check("MD5(\"abc\") matches RFC 1321",
              hexeq(d, "900150983cd24fb0d6963f7d28e17f72", 16));

        /* SHA3-256, which is Keccak and a different code path entirely
         * — and one of the files that had to be recompiled when the x86
         * architecture flag went in. */
        gcry_md_hash_buffer(GCRY_MD_SHA3_256, d, "abc", 3);
        check("SHA3-256(\"abc\") matches NIST",
              hexeq(d, "3a985da74fe225b2045c172d6bd390bd"
                       "855f086e3e9d525b46bfe24511431532", 32));
    }

    /* ---- 3. HMAC, RFC 4231 test case 2 ---- */
    {
        gcry_mac_hd_t h;
        unsigned char mac[32];
        size_t len = sizeof(mac);
        check("a MAC handle opens",
              gcry_mac_open(&h, GCRY_MAC_HMAC_SHA256, 0, NULL) == 0);
        gcry_mac_setkey(h, "Jefe", 4);
        gcry_mac_write(h, "what do ya want for nothing?", 28);
        check("HMAC-SHA256 finishes", gcry_mac_read(h, mac, &len) == 0);
        check("and matches RFC 4231 case 2",
              hexeq(mac, "5bdcc146bf60754e6a042426089575c7"
                         "5a003f089d2739839dec58b964ec3843", 32));
        gcry_mac_close(h);
    }

    /* ---- 4. AES, FIPS 197 ---- */
    {
        gcry_cipher_hd_t c;
        /* FIPS 197 appendix B: key 000102...0f, plaintext 00112233...ff. */
        static const unsigned char key[16] = {
            0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,
            0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f };
        static const unsigned char pt[16] = {
            0x00,0x11,0x22,0x33,0x44,0x55,0x66,0x77,
            0x88,0x99,0xaa,0xbb,0xcc,0xdd,0xee,0xff };
        unsigned char ct[16], back[16];

        check("an AES-128 handle opens",
              gcry_cipher_open(&c, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_ECB, 0) == 0);
        check("the key is accepted", gcry_cipher_setkey(c, key, 16) == 0);
        check("it encrypts",
              gcry_cipher_encrypt(c, ct, 16, pt, 16) == 0);
        /*
         * This is the check the whole "no assembly" decision rests on.
         * The portable C rijndael is what ran; a distribution build would
         * have used AES-NI. The answer must be the same answer.
         */
        check("AES-128 matches FIPS 197 appendix B",
              hexeq(ct, "69c4e0d86a7b0430d8cdb78070b4c55a", 16));

        gcry_cipher_reset(c);
        check("and decrypts back",
              gcry_cipher_decrypt(c, back, 16, ct, 16) == 0 &&
              memcmp(back, pt, 16) == 0);
        gcry_cipher_close(c);
    }

    /* ---- 5. AES-GCM, NIST test case 2 ---- */
    {
        gcry_cipher_hd_t c;
        static const unsigned char key[16] = { 0 };
        static const unsigned char iv[12]  = { 0 };
        unsigned char pt[16] = { 0 };
        unsigned char ct[16], tag[16];

        check("a GCM handle opens",
              gcry_cipher_open(&c, GCRY_CIPHER_AES128, GCRY_CIPHER_MODE_GCM, 0) == 0);
        gcry_cipher_setkey(c, key, 16);
        gcry_cipher_setiv(c, iv, 12);
        check("GCM encrypts", gcry_cipher_encrypt(c, ct, 16, pt, 16) == 0);
        check("the ciphertext matches NIST case 2",
              hexeq(ct, "0388dace60b6a392f328c2b971b2fe78", 16));
        check("the tag comes out", gcry_cipher_gettag(c, tag, 16) == 0);
        check("and matches NIST case 2",
              hexeq(tag, "ab6e47d42cec13bdf53a67b21257bddf", 16));
        gcry_cipher_close(c);
    }

    /* ---- 6. PBKDF2, RFC 6070 ---- */
    {
        unsigned char out[20];
        check("PBKDF2 runs",
              gcry_kdf_derive("password", 8, GCRY_KDF_PBKDF2, GCRY_MD_SHA1,
                              "salt", 4, 2, sizeof(out), out) == 0);
        check("and matches RFC 6070 with c=2",
              hexeq(out, "ea6c014dc72d6f8ccd1ed92ace1d41f0d8de8957", 20));
    }

    /* ---- 7. the random generator ---- */
    {
        unsigned char r[32];
        memset(r, 0, sizeof(r));
        gcry_randomize(r, sizeof(r), GCRY_STRONG_RANDOM);
        int nz = 0;
        for (unsigned i = 0; i < sizeof(r); i++) if (r[i]) nz++;
        /*
         * Thirty-two zero bytes out of a generator is not entropy, it is
         * a wire that is not connected — and the wire here is
         * rndgetentropy, over libc's getentropy, over SYS_RANDOM, over
         * RDSEED. Four of libgcrypt's five backends were left out; this
         * checks that the one compiled in reaches the processor.
         */
        check("gcry_randomize produces something", nz > 0);

        unsigned char r2[32];
        gcry_randomize(r2, sizeof(r2), GCRY_STRONG_RANDOM);
        check("and something different the second time",
              memcmp(r, r2, sizeof(r)) != 0);
    }

    /* ---- 8. the generated errno table ---- */
    {
        /*
         * The check nothing else in this file can make.
         *
         * libgpg-error's code-from-errno.h is built at build time by
         * preprocessing errnos.in and running a small program over the
         * result. The preprocessing has to be done by the *cross*
         * compiler against libc/include/errno.h, because these numbers
         * are this system's: EOPNOTSUPP is 95 here and 102 on the
         * machine doing the building. Every algorithm above passes
         * whichever preprocessor was used.
         */
        check("errno 2 maps to GPG_ERR_ENOENT",
              gcry_err_code_from_errno(ENOENT) == GPG_ERR_ENOENT);
        check("errno 13 maps to GPG_ERR_EACCES",
              gcry_err_code_from_errno(EACCES) == GPG_ERR_EACCES);
        /* The one whose number differs between this system and the
         * machine that built it. */
        check("errno 95 maps to GPG_ERR_EOPNOTSUPP",
              gcry_err_code_from_errno(EOPNOTSUPP) == GPG_ERR_EOPNOTSUPP);
        check("and the mapping goes back the other way",
              gcry_err_code_to_errno(GPG_ERR_EOPNOTSUPP) == EOPNOTSUPP);

        /* And that an error can name itself, which needs strsource.c and
         * strerror.c and the two string tables the tarball ships. */
        const char *msg = gcry_strerror(gcry_error(GPG_ERR_ENOMEM));
        check("an error code has a message", msg && msg[0]);
        /*
         * And that an error names a *source*, which is a separate table
         * from the message one.
         *
         * The source here is "unknown", and that is correct rather than
         * a shortcoming: gcry_error() stamps GPG_ERR_SOURCE_DEFAULT, and
         * that macro is whatever the *including* program defined it to
         * be. libgcrypt's own sources define it to GPG_ERR_SOURCE_GCRYPT
         * in config.h; an application that includes only <gcrypt.h>, as
         * this one does, has not claimed a source and gets the honest
         * answer. What is checked is that the table is present and
         * answers at all — a missing strsource.c would give null.
         */
        const char *src = gcry_strsource(gcry_error(GPG_ERR_ENOMEM));
        check("and an error source has a name", src && src[0]);
    }

    /* ---- 9. what it says it is ---- */
    {
        const char *cfg = gcry_get_config(0, NULL);
        check("gcry_get_config answers", cfg != NULL);
        /* The bignum layer reports which sources it was built from, and
         * for this build the honest answer is the portable C — see
         * mod-source-info.h, generated by the Makefile. */
        check("and reports the generic bignum",
              cfg && strstr(cfg, "generic C") != NULL);
    }

    printf("gcrypttest: %d checks, %d failures\n", checks, failures);
    return failures ? 1 : 0;
}
